# Site settings
title: Ivan Podovalov CV 
description: Podovalov's CV
favicon: /assets/img/image.jpg
baseurl: https://ipodovalov.github.io/
url: https://ipodovalov.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ivan Podovalov
  title: C/C++/Linux/Embedded Developer
  address: Moscow region, Russia
  email: ipodovalov@gmail.com
  link: https://ipodovalov.github.io
  weibo:
  github: ipodovalov
  linkedin: ipodovalov
  twitter: ipodovalov
  gavatar: /assets/img/image.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: VNIKTI, Center for Scientific Research in Transport Engineering
      location: Kolomna, Moscow region, Russia
      title: C/C++/Linux/Embedded Developer
      started: 2014
      duration: (2014 - Present)
      description: Participate in full software development cycle according to customer requests. Review code others developers and project files. Developing, alteration and testing embedded firmware for different devices.
    - work2:
      company: Rostelecom
      location: Moscow, Russia
      title: Engineer
      started: 2009
      duration: (2011 - 2014)
      description: Writing scripts in Bash for work optimization process. 
    - work3:
      company: SimSim 
      location: Kolomna, Moscow region, Russia
      title: System administrator, Network administrator
      started: 2009
      duration: (2009 - 2012)
      description: Management of infrastructure servers and services: Zabbix, DHCP. Support of field engineers during installation and maintenance of remote servers.
  educationHistory:
    - education1: 
      organization: Moscow Polytechnic University
      location: Moscow, Russia
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2010)
      description: 
  languages:
    - language1:
      name: Russian
      proficiency: Native
    - language2:
      name: English
      proficiency: Pre Intermediate
    - language3:
      name: Hebrew
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C
      percentage: 90%
    - skill2:
      name: C++
      percentage: 60%
    - skill3:
      name: Bash
      percentage: 90%
    - skill4:
      name: Python
      percentage: 40%
    - skill5:
      name: Java/Java EE
      percentage: 20%
