# Site settings
title: Ivan Podovalov CV 
description: Podovalov's CV
favicon: /assets/img/image.jpg
baseurl: https://ipodovalov.github.io/
url: https://ipodovalov.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ivan Podovalov
  title: C/C++/Linux/Embedded Developer
  address: Moscow region, Russia
  email: ipodovalov@gmail.com
  link: https://ipodovalov.github.io
  weibo:
  github: ipodovalov
  linkedin: ipodovalov
  twitter: ipodovalov
  gavatar: /assets/img/image.jpg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: XXXXXX University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Russian
      proficiency: Native
    - language2:
      name: English
      proficiency: Pre Intermediate
    - language3:
      name: Hebrew
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C
      percentage: 90%
    - skill2:
      name: C++
      percentage: 60%
    - skill3:
      name: Bash
      percentage: 90%
    - skill4:
      name: Python
      percentage: 50%
    - skill5:
      name: Java/Java EE
      percentage: 20%
